[toolchain]
channel = "1.85"
profile = "default"
components = ["rust-analyzer"]
targets = [
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "i686-pc-windows-msvc",
]
