name: Renovate Dependency Updates
on:
  schedule:
    - cron: "0 6 * * 1,3,5" # 14:00 AWST on Mondays, Wednesdays, Fridays
  workflow_dispatch: # Allow manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@67e27a7eb7db372a1c61a7f9bdab8699e9ee57f7
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Run Renovate
        uses: renovatebot/github-action@e084b5ac6fd201023db6dd7743aec023babb02c8
        with:
          configurationFile: .github/renovate.config.js
          token: ${{ steps.get_token.outputs.token }}
        env:
          RENOVATE_PLATFORM_COMMIT: true
